package App::Autopod::Template::Module;

use strict;
use warnings;
use IO::Scalar;

sub priority {
    return 200;
}

# Determines if the current plugin can be used
# with the desired file or content
sub is_applicable {
    my ($self, $filename, $content) = @_;

    if ($filename !~ m{.+\.[pP][mM]$}) {
        return 0;
    }

    if ($content !~ m{^package \s+ \S+}ms) {
        return 0;
    }

    return 1;
}

sub as_filehandle {
    my $content = content();
	return IO::Scalar->new(\$content);
}

sub as_string {

	my $content = q~
=pod

=head1 NAME

[% class %] - [% class_description %]

=head1 SYNOPSIS

Here you should fill in the synopsis of [% class %]

    my $obj = [% class %]->new();

    $obj->method1($args, ...);
    $obj->method2(...);

    my $result = $obj->method3($args);

    ...

=head1 DESCRIPTION

Fill in the description of [% class %]

=head1 SUBROUTINES/METHODS

=head2 AUTOGENERATED FUNCTIONS

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
You have to move the following functions to class or instance sections
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

[% functions %]

=head2 CLASS METHODS

=head3 C<new( [\%args] )>

Class constructor. Describe optional mandatory or
additional arguments if any.

If there's missing or invalid arguments, it returns
an undefined value.

Example:

    my $obj = [% class %]->new();

=head2 INSTANCE METHODS

=head3 C<some_method($arg1, $arg2, ...)>

Accelerates to warp speed.

C<$arg1> is the acceleration factor.
C<$arg2> is the warp target speed.

Returns a boolean value that tells you if the
acceleration is possible or not.

=head1 BUGS AND LIMITATIONS

*** Here you should fill in your bug tracker
information, if you have one.

=head1 SEE ALSO

*** Other stuff to be looked into, if any

=over 4

=item * this one

=item * that one

=back

=head1 AUTHOR

[% fullname %], E<lt>[% email %]E<gt>

=head1 LICENSE AND COPYRIGHT

Copyright (c), [% year %] [% copyright_holder %]
All rights reserved.

~;

    return $content;
}

1;

